# Generated by Django 5.2.15 on 2026-06-19 13:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
                ('avatar_url', models.URLField(blank=True)),
                ('preview_track_url', models.URLField(blank=True, help_text='30 секунд музыки для режима «Волна»')),
                ('mood_profile', models.JSONField(blank=True, help_text='Настроение: energy, valence, tempo и т.д.', null=True)),
                ('music_embedding', models.JSONField(blank=True, help_text='Вектор для ML-матчинга (заполнит ML Engineer)', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'профиль',
                'verbose_name_plural': 'профили',
            },
        ),
    ]
