# Generated by Django 5.2.15 on 2026-06-19 13:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('spotify', 'Spotify'), ('lastfm', 'Last.fm'), ('soundcloud', 'SoundCloud'), ('yandex', 'Яндекс Музыка')], max_length=20)),
                ('external_user_id', models.CharField(max_length=128)),
                ('tokens_encrypted', models.JSONField(blank=True, help_text='OAuth-токены (Week 2+)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'подключение сервиса',
                'verbose_name_plural': 'подключения сервисов',
            },
        ),
        migrations.CreateModel(
            name='MusicTaste',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('spotify', 'Spotify'), ('lastfm', 'Last.fm'), ('soundcloud', 'SoundCloud'), ('yandex', 'Яндекс Музыка')], max_length=20)),
                ('external_artist_id', models.CharField(max_length=128)),
                ('artist_name', models.CharField(max_length=255)),
                ('weight', models.FloatField(default=1.0)),
            ],
            options={
                'verbose_name': 'музыкальный вкус',
                'verbose_name_plural': 'музыкальные вкусы',
            },
        ),
    ]
