# Generated by Django 5.2.15 on 2026-06-19 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicconnection',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_connections', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='musictaste',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_tastes', to='profiles.profile'),
        ),
        migrations.AddConstraint(
            model_name='musicconnection',
            constraint=models.UniqueConstraint(fields=('profile', 'provider'), name='unique_profile_provider'),
        ),
    ]
