# Generated by Django 5.2.15 on 2026-06-19 13:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('archived', 'В архиве')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'матч',
                'verbose_name_plural': 'матчи',
            },
        ),
        migrations.CreateModel(
            name='WaveSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('listening', 'Слушает'), ('revealed', 'Профиль открыт'), ('messaged', 'Написал'), ('skipped', 'Пропустил')], default='listening', max_length=20)),
                ('listen_duration_sec', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'сессия «Волна»',
                'verbose_name_plural': 'сессии «Волна»',
            },
        ),
    ]
